# Generated by Django 3.2.5 on 2021-07-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_id',
            field=models.IntegerField(),
        ),
    ]
